CREATE TABLE IF NOT EXISTS cards(
id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
encrypted_number VARCHAR(512) NOT NULL,
holder_name VARCHAR(128) NOT NULL,
expiry_date DATE NOT NULL,
status VARCHAR(32) NOT NULL,
balance NUMERIC(19, 2) DEFAULT 0 NOT NULL,
user_id BIGINT NOT NULL,
version BIGINT DEFAULT 0 NOT NULL,
CONSTRAINT fk_cards_users FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS pre_generated_card (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    card_number_encrypted VARCHAR(512) NOT NULL
);